name: hexo_deploy
on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
  workflow_dispatch:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v2
      
      - name: Set-up Node Env
        uses: actions/setup-node@v1
        with:
          node-version: v12

      - name: Set-up Enviroment Config
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DEPLOY_KEY_PRI }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "timmycheng"
          git config --global user.email "timmycheng@foxmail.com"

      - name: Install dependencies
        run: |
          npm install hexo -g
          npm install

      - name: Deploy hexo
        run: hexo g && hexo d
      
      

  