name: hexo_deploy
on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
  workflow_dispatch:
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: CheckOut
        uses: actions/checkout@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      
      - name: Set-up Node Env
        uses: actions/setup-node@v3
        with:
          node-version: v16

      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: pages

      - name: notify
        # env:
          # messages: ${{ github.event.commits.*.message }}
        run: |
          curl --request POST \
          --url http://wxpusher.zjiecode.com/api/send/message \
          --header 'Content-Type: application/json' \
          --data '{
            "appToken":"${{ secrets.wxpusher_token }}",
            "summary":"${{ join(github.event.commits.*.message, ', ') push完成!",
            "content":"本次提交内容：${{ join(github.event.commits.*.message, ', ') }}",
            "contentType":1,
            "uids":[
                "${{ secrets.uid }}"
            ],
            "url":"https://timmycheng.cn"
          }' \
      
      

  