# This is a basic workflow to help you get started with Actions

name: push_notify

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  notify:

    runs-on: ubuntu-latest

    steps:
      - name: wxpusher
        uses: lxzxl/wxpusher-action@v1
        with:
          appToken: ${{ secrets.wxpusher_token}}
          content: "This is from github action"
          uids: ${{ secrets.uid }}