# This is a basic workflow to help you get started with Actions

name: test

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
    paths:
      - ".github/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  notify:

    runs-on: ubuntu-latest

    steps:
      - name: show github content
        run: echo ${{ toJSON(github) }}